## 1 )

In [2]:
import numpy as np

## 2 )

In [9]:
print(np.__version__)

1.18.5


## 3 )

In [13]:
v = np.zeros(10)

## 4)

In [15]:
v[4] = 1
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 5)

In [19]:
Z = np.arange(start=10, stop=51)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


## 6)

In [21]:
np.flip(Z) 

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

## 7)

In [35]:
M = np.random.randint(8, size=(3, 3))
print(M)

[[6 2 7]
 [6 3 4]
 [3 1 5]]


## 8)

In [25]:
Id = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(Id)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


## 9)

In [34]:
M2 = np.random.randint(10, size=(3, 3, 3))
print(M2)

[[[4 0 7]
  [4 9 8]
  [3 6 9]]

 [[8 9 7]
  [2 9 7]
  [4 6 8]]

 [[3 1 0]
  [6 0 7]
  [6 2 1]]]


## 10)

In [37]:
M3 = np.random.randint(10, size=(10, 10))
print(M3)

[[3 2 2 5 5 4 0 6 9 7]
 [2 4 7 1 6 5 2 2 2 8]
 [6 4 9 7 4 8 9 9 2 8]
 [7 3 2 2 5 4 6 6 7 1]
 [3 7 2 8 0 4 0 7 6 5]
 [4 3 8 4 8 4 0 3 4 9]
 [9 5 2 8 2 7 5 7 2 7]
 [6 7 7 6 0 3 1 4 6 6]
 [3 4 8 5 4 3 0 3 6 8]
 [7 7 2 7 5 0 4 1 9 8]]


In [38]:
np.min(M3)

0

In [39]:
np.max(M3)

9

## 11)

In [40]:
M4 = np.random.randint(10, size=(5, 5))
print(M4)

[[1 4 4 0 3]
 [5 2 4 8 8]
 [8 0 2 3 1]
 [2 0 0 9 1]
 [3 2 5 3 4]]


In [92]:
M5 = np.arange(25).reshape((5,5))
M5[np.diag_indices(5)] = 1
M5.fill_diagonal(-1, [1 2 3 4])
print(M5)
print(M5.diagonal(-1))

SyntaxError: invalid syntax (<ipython-input-92-ddb29a969893>, line 3)

## 12)

In [23]:
list = np.random.randint(10, size=5)
print(sum(list))

21


## 13)

In [25]:
print(np.mean(list))

4.2


## 14)

In [27]:
l = [x for x in range(11)]
print(len(l))

11


## 15)

In [28]:
print(np.random.rand(10))

[0.05956098 0.15010598 0.1343736  0.3628987  0.8287618  0.33463311
 0.06402536 0.62324713 0.40286117 0.73408664]


## 16)

In [32]:
A = np.random.randint(10, size=5)
B = np.random.randint(10, size=5)
print(np.array_equal(A,B))

False


## 17)

In [39]:
a = np.array([1, 2, 3, 4], dtype=np.float64)
print(a)
a = a.astype(np.int32)
print(a)

[1. 2. 3. 4.]
[1 2 3 4]


## 18)

In [49]:
x= np.random.randint(10, size=(5, 5))
print((x - np.mean(x)) / np.std(x))

[[-0.290989    1.36235759 -1.28299695  0.70101895 -0.62165832]
 [ 0.37034964  0.70101895  0.70101895 -0.95232763 -1.28299695]
 [ 1.03168827  1.6930269  -0.290989    0.03968032  0.03968032]
 [ 1.36235759 -1.28299695 -1.28299695 -0.62165832 -0.290989  ]
 [-1.28299695  0.03968032 -1.28299695  1.6930269   1.03168827]]


## 19)

In [46]:
x2 = np.arange(4).reshape((2,2))
print(x2)
np.transpose(x2)

[[0 1]
 [2 3]]


array([[0, 2],
       [1, 3]])

## 20)

In [88]:
x3 = np.arange(4).reshape((2,2))
print(x3)
inds = np.random.choice(2, size=1)   # Get random indices
x3[inds] = np.random.normal(size=1)        # Fill with something
x3 = x3.reshape(x3.shape)   
print(x3)

[[0 1]
 [2 3]]
[[ 0  1]
 [-1 -1]]


## 21)

In [89]:
A = np.array([[1,2,0],[4,3,-1]])
B = np.array([[5,1],[2,3],[3,4]])
print(A.dot(B))

[[ 9  7]
 [23  9]]
